### ISSUE TITLE
添加webpack编译错误提示插件 friendly-errors-webpack-plugin 无效

### ISSUE THREAD

**Issue by Lucianing** [Jines-z/rs-compiler#1]
一旦语法错误，页面会出现一片空白情况，想添加类似 create-react-app 的 react-error-overlay 的插件，找了这个 friendly-errors-webpack-plugin，添加后仍然没有效果。看插件源码基于 compiler.hooks.done.tap('done', stats => {}) hook实现的，但是无法获取到错误对象，为啥呢？

想实语法错误时现类似这种效果：
![image](https://user-images.githubusercontent.com/33444972/62858462-fd749f00-bd2c-11e9-9803-72beb1d5b549.png)

**Comment by Jines-z** [comment]
经测试发现，第一次启动时（也就是npm start时）就已经包含错误代码的话，就会白屏，因为中断了编译，浏览器与本地的server并没有链接成功，所以改过代码以后浏览器也不会刷新。
若是正常启动的情况下，你在控制台看到一个已连接的打印 [HMR] connected，这时再写错误代码能看到错误提示，如下图，并且不会中断connect。
![QQ图片20191009145753](https://user-images.githubusercontent.com/22887299/66458845-4f743f80-eaa6-11e9-915f-9b3616afed11.png)
